### ISSUE TITLE
Protoc compile

### ISSUE THREAD

**Issue by YangBain** [kujason/avod#23] opened 2018-03-26 00:52 UTC
Anyone who knows how to solve this problems when I compile protoc from the avod folder. Thanks.

avod/protos/kitti_utils.proto:24:5: Expected "required", "optional", or "repeated".
avod/protos/kitti_utils.proto:24:25: Missing field number.
avod/protos/kitti_dataset.proto: Import "avod/protos/kitti_utils.proto" was not found or had errors.
avod/protos/kitti_dataset.proto:39:14: "KittiUtilsConfig" is not defined.

**Comment by melfm** [comment] 2018-03-26 02:30
Duplicate of #2. Closing.

**Closed by melfm** 2018-03-26 02:30 UTC
